#!/usr/bin/env python3
"""Generates supabase/seed.sql. Edit this file, never the .sql.

Demo data for Pivot Charlie: the Nodus workspace, every model the warranty
sheet mentions with a parts catalog covering all ten components, one demo
sign-in per role, and the tickets the mocks show (one per stage plus closed
ones). Deterministic ids (a0000000-0000-4000-8000-0000000NNNNN) so the file
can be re-run: demo tickets are reset, tickets created in the app are kept.

    python3 supabase/seed.py > supabase/seed.sql
    supabase db query --linked --file supabase/seed.sql
"""
from __future__ import annotations

import json


def uid(n: int) -> str:
    return f"a0000000-0000-4000-8000-{n:012d}"


def q(v) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (dict, list)):
        return "'" + json.dumps(v).replace("'", "''") + "'::jsonb"
    return "'" + str(v).replace("'", "''") + "'"


def days(n: float) -> str:
    return f"now() - interval '{n} days'"


out: list[str] = []


def emit(s: str = "") -> None:
    out.append(s)


# ------------------------------------------------------------------ tenancy
WS = uid(1)
NODUS = uid(11)
DEMO_PASSWORD = "PivotDemo2026!!"

BENCH = {"name": "Rane · Pivot Service Center", "line1": "2110 Harbor Ave SW", "city": "Seattle", "state": "WA", "postal_code": "98126", "country": "US"}
# Placeholder until Nodus gives the real fulfillment address.
EVERETT = {"name": "Nodus Fulfillment", "line1": "1000 Fulfillment Way", "city": "Everett", "state": "WA", "postal_code": "98201", "country": "US"}

emit("-- GENERATED by supabase/seed.py — edit that file, not this one.")
emit("-- Demo data for Pivot Charlie. Idempotent; demo tickets are reset on each run.")
emit()
emit("insert into workspaces (id, name, slug, ticket_prefix, bench_address, fulfillment_address) values")
emit(f"  ({q(WS)}, 'Nodus', 'nodus', 'NW', {q(BENCH)}, {q(EVERETT)})")
emit("on conflict (id) do update set name = excluded.name, ticket_prefix = excluded.ticket_prefix,")
emit("  bench_address = coalesce(workspaces.bench_address, excluded.bench_address),")
emit("  fulfillment_address = coalesce(workspaces.fulfillment_address, excluded.fulfillment_address);")
emit()
emit("insert into brands (id, workspace_id, name, slug) values")
emit(f"  ({q(NODUS)}, {q(WS)}, 'Nodus', 'nodus')")
emit("on conflict (id) do nothing;")
emit()

# ------------------------------------------------------------------ catalog
# (id, name, reference, movement, case, notes)
WATCHES = [
    (101, "Sector Deep", "NW-SD-01", "NH35", "40mm · steel", None),
    (102, "Avalon II", "NW-AV2-01", "NH35", "38mm · steel", None),
    (103, "Sector GMT", "NW-SGMT-01", "NH34 GMT", "40mm · steel", None),
    (104, "Contrail GMT", "NW-CT-01", "NH34 GMT", "40mm · steel", "Ceramic insert only from 2025 on"),
    (105, "Canyon", "NW-CYN-01", "NH35", "38mm · titanium", None),
    (106, "Retrospect", "NW-RS-03", "NH35", "38mm · steel", None),
    (107, "Sector Pilot", "NW-SP-01", "NH35", "40mm · steel", None),
    (108, "Sector Sport", "NW-SS-01", "NH35", "40mm · steel", None),
    (109, "Contrail II", "NW-CT2-01", "NH35", "40mm · steel", "Sapphire inlay bezel"),
    (110, "Duality", "NW-DU-01", "NH35", "38mm · steel", "Inner rotating bezel"),
    (111, "TrailTrekker", "NW-TT-01", "NH35", "40mm · carbon", None),
    (112, "Obscura", "NW-OB-01", "NH35", "38mm · steel", None),
]
SD, AV2, SGMT, CT, CYN, RS, SP, SS, CT2, DU, TT, OB = (w[0] for w in WATCHES)
ALL = [w[0] for w in WATCHES]
SECTOR = [SD, SGMT, SP, SS]
CONTRAIL = [CT, CT2]
GMT = [SGMT, CT]
NON_GMT = [w for w in ALL if w not in GMT]
MM40 = [SD, SGMT, CT, SP, SS, CT2, TT]
MM38 = [AV2, CYN, RS, DU, OB]
SHORT = {SD: "SD", AV2: "AV2", SGMT: "SGMT", CT: "CT", CYN: "CYN", RS: "RS", SP: "SP", SS: "SS", CT2: "CT2", DU: "DU", TT: "TT", OB: "OB"}
NAME = {w[0]: w[1] for w in WATCHES}

# (sku, name, component, variant, fits)
PARTS: list[tuple[str, str, str, str | None, list[int]]] = [
    ("GK-UNI-01", "Gasket set", "gaskets", None, ALL),
    ("CL-NW-01", "Nodus clasp, signed", "clasp", None, ALL),
    ("CL-NX-16", "NodeX module, 16mm", "clasp", "16mm", ALL),
    ("CL-NX-18", "NodeX module, 18mm", "clasp", "18mm", ALL),
    ("CR-NW-01", "Crown, signed", "crown", None, ALL),
    ("CT-NW-01", "Casetube", "crown", None, ALL),
    ("MV-NH35", "NH35 movement", "movement", None, NON_GMT),
    ("MV-NH34", "NH34 GMT movement", "movement", None, GMT),
    ("CRY-40-01", "Sapphire crystal, 40mm", "crystal", None, MM40),
    ("CRY-38-01", "Sapphire crystal, 38mm", "crystal", None, MM38),
    ("BZ-SD-01", "Bezel insert, Sector Deep", "bezel", "Ceramic", [SD]),
    ("BZ-SGMT-24", "Bezel insert, Sector GMT 24h", "bezel", None, [SGMT]),
    ("BZ-CT-01", "Bezel insert, Contrail", "bezel", "Ceramic", [CT]),
    ("BZ-CT-02", "Bezel insert, Contrail", "bezel", "Steel-Alu", [CT]),
    ("BZ-CT2-01", "Sapphire inlay, Contrail II", "bezel", "Sapphire", [CT2]),
    ("BZ-AV2-01", "Bezel insert, Avalon II", "bezel", "Steel", [AV2]),
    ("BZ-CYN-01", "Bezel insert, Canyon", "bezel", None, [CYN]),
    ("BZ-RS-01", "Bezel insert, Retrospect", "bezel", None, [RS]),
    ("BZ-SP-01", "Bezel insert, Sector Pilot", "bezel", None, [SP]),
    ("BZ-SS-01", "Bezel insert, Sector Sport", "bezel", None, [SS]),
    ("BZ-DU-01", "Inner bezel, Duality", "bezel", None, [DU]),
    ("BZ-TT-01", "Bezel, TrailTrekker lumed", "bezel", None, [TT]),
    ("BZ-OB-01", "Bezel insert, Obscura", "bezel", None, [OB]),
    ("HD-CT-GMT", "GMT hand", "hands", None, [CT]),
    ("HD-SGMT-GMT", "GMT hand, Sector", "hands", None, [SGMT]),
    ("BR-SEC-01", "Sector bracelet", "strap", None, SECTOR),
    ("BR-CT-01", "Contrail bracelet", "strap", None, CONTRAIL),
    ("BR-AV2-01", "Avalon bracelet", "strap", None, [AV2]),
    ("BR-CYN-01", "Canyon bracelet", "strap", None, [CYN]),
    ("BR-RS-01", "Beads of rice bracelet", "strap", None, [RS]),
    ("BR-DU-01", "Duality bracelet", "strap", None, [DU]),
    ("BR-TT-01", "TrailTrekker rubber strap", "strap", None, [TT]),
    ("BR-OB-01", "Obscura bracelet", "strap", None, [OB]),
]
for w in ALL:
    s = SHORT[w]
    PARTS.append((f"DL-{s}-01", f"Dial, {NAME[w]}", "dial", None, [w]))
    PARTS.append((f"HD-{s}-01", f"Hands set, {NAME[w]}", "hands", None, [w]))
    PARTS.append((f"CS-{s}-01", f"Case, {NAME[w]}", "case", None, [w]))

COMPONENTS = ["bezel", "crystal", "crown", "case", "dial", "hands", "movement", "gaskets", "strap", "clasp"]
for w in ALL:
    covered = {p[2] for p in PARTS if w in p[4]}
    missing = set(COMPONENTS) - covered
    assert not missing, f"watch {w} missing {missing}"

PART_ID = {sku: uid(200 + i) for i, (sku, *_rest) in enumerate(PARTS)}

emit("-- ---------------------------------------------------------------- catalog (demo)")
emit("insert into watches (id, workspace_id, brand_id, name, reference, warranty_months, movement, case_spec, notes) values")
emit(",\n".join(f"  ({q(uid(i))}, {q(WS)}, {q(NODUS)}, {q(n)}, {q(r)}, 24, {q(mv)}, {q(cs)}, {q(notes)})" for i, n, r, mv, cs, notes in WATCHES))
emit("on conflict (id) do update set name = excluded.name, reference = excluded.reference, movement = excluded.movement, case_spec = excluded.case_spec, notes = excluded.notes, is_active = true;")
emit()
emit("insert into parts (id, workspace_id, brand_id, component, name, sku, variant) values")
emit(",\n".join(f"  ({q(PART_ID[sku])}, {q(WS)}, {q(NODUS)}, {q(comp)}, {q(name)}, {q(sku)}, {q(var)})" for sku, name, comp, var, _ in PARTS))
emit("on conflict (id) do update set component = excluded.component, name = excluded.name, sku = excluded.sku, variant = excluded.variant, is_active = true;")
emit()
emit("-- Fits are demo configuration: reset them for the demo watches.")
emit(f"delete from watch_parts where watch_id in ({', '.join(q(uid(w)) for w in ALL)});")
emit("insert into watch_parts (watch_id, part_id) values")
emit(",\n".join(f"  ({q(uid(w))}, {q(PART_ID[sku])})" for sku, _, _, _, fits in PARTS for w in fits))
emit("on conflict do nothing;")
emit()

# ------------------------------------------------------------------ people
USERS = [
    (901, "owner.demo@pivot.test", "Wes (demo)", [("owner", None, None)]),
    (902, "cullen.demo@pivot.test", "Cullen (demo)", [("owner", None, None)]),
    (903, "rane.demo@pivot.test", "Rane (demo)", [("watchmaker", None, NODUS)]),
    (904, "nodus.rep.demo@pivot.test", "Nodus rep (demo)", [("brand_rep", None, NODUS)]),
]
WES, CULLEN, RANE, REP = (uid(n) for n in (901, 902, 903, 904))
emit("-- ---------------------------------------------------------------- demo people")
emit(f"-- Every demo sign-in uses the password {DEMO_PASSWORD!r}. Re-running the seed resets it.")
emit("insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new) values")
emit(",\n".join(
    f"  ({q(uid(i))}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', {q(email)}, extensions.crypt({q(DEMO_PASSWORD)}, extensions.gen_salt('bf')), now(), '{{\"provider\":\"email\",\"providers\":[\"email\"]}}'::jsonb, {q({'display_name': name})}, now(), now(), '', '', '', '')"
    for i, email, name, _ in USERS))
emit("on conflict (id) do update set encrypted_password = excluded.encrypted_password, email_confirmed_at = coalesce(auth.users.email_confirmed_at, now());")
emit()
emit("insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at) values")
emit(",\n".join(
    f"  ({q(uid(950 + k))}, {q(uid(i))}, {q(uid(i))}, 'email', {q({'sub': uid(i), 'email': email, 'email_verified': True})}, now(), now(), now())"
    for k, (i, email, _, _) in enumerate(USERS)))
emit("on conflict (provider_id, provider) do nothing;")
emit()
emit("insert into profiles (id, email, display_name) values")
emit(",\n".join(f"  ({q(uid(i))}, {q(email)}, {q(name)})" for i, email, name, _ in USERS))
emit("on conflict (id) do update set display_name = excluded.display_name, is_active = true;")
emit()
emit("insert into memberships (user_id, role, workspace_id, brand_id) values")
emit(",\n".join(f"  ({q(uid(i))}, {q(role)}, {q(ws)}, {q(b)})" for i, _, _, grants in USERS for role, ws, b in grants))
emit("on conflict (user_id, role, workspace_id, brand_id) do nothing;")
emit()

# ------------------------------------------------------------------ tickets
LA = {"line1": "77 Grand Ave", "city": "Los Angeles", "state": "CA", "postal_code": "90013", "country": "US"}
PATH = ["check_in", "inspect", "supply", "fix", "test", "ship", "closed"]


def addr(line1, city, state, zip_):
    return {"line1": line1, "city": city, "state": state, "postal_code": zip_, "country": "US"}


# Each ticket: a dict describing its state. `age` = days since it was created.
TICKETS = [
    dict(n=1, name="Dana Whitmore", email="dana.w@example.com", watch=SD, stage="check_in", age=30, source="sheet",
         claim="1a0d1be2d8891a0a", serial="5080131", issue="Bezel doesn't click anymore and rotates freely.",
         ship_to=addr("2234 E Wilson Ave", "Salt Lake City", "UT", "84108"), received=False),
    dict(n=2, name="Maria Lopez", email="maria@example.com", watch=AV2, stage="inspect", age=24, source="sheet",
         serial="402376", issue="Second hand stutters and the watch loses about two minutes a day.",
         ship_to=addr("504 2nd St", "Liverpool", "NY", "13088")),
    dict(n=3, name="James Whitfield", email="james@example.com", watch=SGMT, stage="supply", age=22, source="sheet",
         serial="5080093", issue="Crown fell off while setting the time. Dial has a scratch at 10.",
         ship_to=addr("21 Hampshire Rd", "Midland Park", "NJ", "07432"),
         findings=[("dial", "scratched", "replace", "DL-SGMT-01", dict(requested=7)),
                   ("crown", "worn", "replace", "CR-NW-01", dict(have_it=True))],
         message=("Need 1× Dial, Sector GMT DL-SGMT-01 for NW260003", 7)),
    dict(n=4, name="Adam Ferguson", email="adam@example.com", phone="(213) 555-0144", watch=CT, stage="fix", age=12,
         priority=True, coverage="warranty", serial="504004",
         issue="Bezel doesn't click and rotates freely. Deep scratch on the case at 4 o'clock.", ship_to=LA,
         findings=[("bezel", "cracked", "replace", "BZ-CT-01", dict(have_it=True, done=3)),
                   ("case", "scratched", "fix", None, dict()),
                   ("gaskets", "worn", "replace", "GK-UNI-01", dict(requested=11, arrived=8))],
         comments=[(RANE, 9, "Case scratch is deeper than it looked at intake. Polishing, not replacing."),
                   (REP, 7, "Customer asked for an update. Told him early next month.")]),
    dict(n=5, name="Sarah Chen", email="sarah@example.com", watch=SD, stage="test", age=6, coverage="warranty",
         serial="5090367", issue="Fogging under the crystal after swimming.", ship_to=addr("11 Tiburon Court", "Manhattan Beach", "CA", "90266"),
         findings=[("gaskets", "worn", "replace", "GK-UNI-01", dict(have_it=True, done=2)),
                   ("crystal", "discolored", "fix", None, dict(done=2))],
         tests=[(1, "time", "pass"), (1, "water", "pass")]),
    dict(n=6, name="Leo Park", email="leo@example.com", watch=AV2, stage="ship", age=9, coverage="warranty",
         serial="402385", issue="Running slow, needs regulation.", ship_to=addr("2459 Decatur St", "Denver", "CO", "80211"),
         findings=[("movement", "worn", "fix", None, dict(done=2))],
         tests=[(1, "time", "pass"), (1, "water", "pass"), (1, "looks", "pass")],
         shipment=dict()),
    dict(n=7, name="Priya Nair", email="priya@example.com", watch=CT, stage="closed", age=40, closed=36, coverage="warranty",
         serial="504018", issue="Lume barely glows on the hour markers.", ship_to=addr("9337 Hillside Dr", "Champlin", "MN", "55316"),
         findings=[("dial", "discolored", "replace", "DL-CT-01", dict(have_it=True, done=38))],
         tests=[(1, "time", "pass"), (1, "water", "pass"), (1, "looks", "pass")],
         shipment=dict(carrier="usps", tracking="9400 1108 4007 2231 0001", shipped=36)),
    dict(n=8, name="Tom Reyes", email="tom@example.com", watch=SGMT, stage="closed", age=50, closed=44, coverage="paid",
         needs_payment=True, payment_amount=55, payment_received=True,
         serial="5030761", issue="Clasp would not stay closed. Out of warranty.", ship_to=addr("7218 Murray Lane", "Annandale", "VA", "22003"),
         findings=[("clasp", "worn", "replace", "CL-NW-01", dict(have_it=True, done=46))],
         tests=[(1, "time", "pass"), (1, "water", "pass"), (1, "looks", "fail"),
                (2, "time", "pass"), (2, "water", "pass"), (2, "looks", "pass")],
         sent_back=47,
         shipment=dict(carrier="ups", tracking="1Z 999 AA1 01 2345 6784", shipped=44)),
    dict(n=9, name="Owen Brooks", email="owen@example.com", watch=TT, stage="check_in", age=2, return_to_everett=True,
         serial="1292", issue="New watch arrived with a divot in the bezel near 10. Customer is returning it.",
         ship_to=addr("35475 Marabella Ct", "Winchester", "CA", "92596")),
]

ticket_rows, finding_rows, test_rows, ship_rows, event_rows = [], [], [], [], []
eid = 4300
fid = 4100
xid = 4500
sid = 4600
ticket_ids = []

for t in TICKETS:
    tid = 4000 + t["n"]
    ticket_ids.append(tid)
    number = f"NW26{t['n']:04d}"
    stage = t["stage"]
    reached = PATH.index(stage)
    age = t["age"]
    closed_age = t.get("closed")
    received = t.get("received", True)
    ticket_rows.append(
        f"  ({q(uid(tid))}, {q(number)}, {q(WS)}, {q(NODUS)}, {q(uid(t['watch']))}, {q(stage)}, {q(t.get('source', 'by_hand'))}, {q(t.get('claim'))}, "
        f"{q(REP)}, {q(t['name'])}, {q(t['email'])}, {q(t.get('phone'))}, {q(t['ship_to'])}, {q(NAME[t['watch']])}, {q(t.get('serial'))}, {q(t['issue'])}, "
        f"{q(t.get('coverage'))}, {q(t.get('priority', False))}, {q(t.get('needs_payment', False))}, {q(t.get('payment_amount'))}, {q(t.get('payment_received', False))}, {q(t.get('return_to_everett', False))}, "
        f"{days(age) if received else 'null'}, {max(a for a, *_ in t.get('tests', [(1,)]))}, {days(closed_age) if closed_age else 'null'}, {days(age)}, {days(max(age - 3 * reached, 0.5))})"
    )
    # timeline: created, then one stage_changed per step reached, evenly spaced
    eid += 1
    event_rows.append(f"  ({q(uid(eid))}, {q(uid(tid))}, 'created', {q(REP)}, null, 'check_in', null, {days(age)})")
    span = age - (closed_age or 0.5)
    for i in range(1, reached + 1):
        at = age - span * i / (reached + (0 if stage == 'closed' else 1))
        actor = REP if PATH[i - 1] == "check_in" else RANE
        if t.get("sent_back") and PATH[i] == "ship":
            # a failed test round trip before the final pass
            eid += 1
            event_rows.append(f"  ({q(uid(eid))}, {q(uid(tid))}, 'sent_back', {q(RANE)}, 'test', 'fix', 'Looks failed: smudge under the crystal', {days(t['sent_back'])})")
            eid += 1
            event_rows.append(f"  ({q(uid(eid))}, {q(uid(tid))}, 'stage_changed', {q(RANE)}, 'fix', 'test', null, {days(t['sent_back'] - 1)})")
        eid += 1
        event_rows.append(f"  ({q(uid(eid))}, {q(uid(tid))}, 'stage_changed', {q(actor)}, {q(PATH[i - 1])}, {q(PATH[i])}, null, {days(at)})")
    if t.get("message"):
        body, when = t["message"]
        eid += 1
        event_rows.append(f"  ({q(uid(eid))}, {q(uid(tid))}, 'parts_requested', {q(RANE)}, null, null, {q(body)}, {days(when)})")
    for actor, when, body in t.get("comments", []):
        eid += 1
        event_rows.append(f"  ({q(uid(eid))}, {q(uid(tid))}, 'comment', {q(actor)}, null, null, {q(body)}, {days(when)})")
    if stage == "closed":
        eid += 1
        event_rows.append(f"  ({q(uid(eid))}, {q(uid(tid))}, 'email_logged', {q(RANE)}, null, null, 'On its way', {days(closed_age)})")
    for comp, cond, action, sku, extra in t.get("findings", []):
        fid += 1
        finding_rows.append(
            f"  ({q(uid(fid))}, {q(uid(tid))}, {q(comp)}, {q(cond)}, {q(action)}, {q(PART_ID[sku]) if sku else 'null'}, 'inspect', "
            f"{q(extra.get('have_it', False))}, {days(extra['requested']) if 'requested' in extra else 'null'}, {days(extra['arrived']) if 'arrived' in extra else 'null'}, "
            f"{days(extra['done']) if 'done' in extra else 'null'}, {q(RANE) if 'done' in extra else 'null'}, {q(RANE)})"
        )
    for attempt, kind, result in t.get("tests", []):
        xid += 1
        test_rows.append(f"  ({q(uid(xid))}, {q(uid(tid))}, {attempt}, {q(kind)}, {q(result)}, {q(RANE)}, {days((closed_age or 1) + 1)})")
    if "shipment" in t:
        s = t["shipment"]
        sid += 1
        ship_rows.append(
            f"  ({q(uid(sid))}, {q(uid(tid))}, {q(s.get('carrier'))}, {q(s.get('tracking'))}, false, true, {q(t['ship_to'])}, "
            f"{days(s['shipped']) if 'shipped' in s else 'null'}, {q(RANE)})"
        )

emit("-- ---------------------------------------------------------------- demo tickets")
emit("-- The bench from the mocks: one ticket per stage plus closed ones. Reset on every run;")
emit("-- tickets created through the app keep their own ids and are never touched.")
emit(f"delete from tickets where id in ({', '.join(q(uid(t)) for t in ticket_ids)});")
emit("alter table tickets disable trigger tickets_updated_at;")
emit("insert into tickets (id, number, workspace_id, brand_id, watch_id, stage, source, claim_ref, created_by, customer_name, customer_email, customer_phone, ship_to, customer_model_text, serial, issue, coverage, priority, needs_payment, payment_amount, payment_received, return_to_everett, received_at, test_attempt, closed_at, created_at, updated_at) values")
emit(",\n".join(ticket_rows) + ";")
emit("alter table tickets enable trigger tickets_updated_at;")
emit()
emit("insert into ticket_events (id, ticket_id, type, actor_id, from_stage, to_stage, body, created_at) values")
emit(",\n".join(event_rows) + ";")
emit()
emit("insert into ticket_findings (id, ticket_id, component, condition, action, part_id, found_at_stage, have_it, requested_at, arrived_at, done_at, done_by, created_by) values")
emit(",\n".join(finding_rows) + ";")
emit()
emit("insert into ticket_tests (id, ticket_id, attempt, kind, result, created_by, created_at) values")
emit(",\n".join(test_rows) + ";")
emit()
emit("insert into shipments (id, ticket_id, carrier, tracking, handed_over, email_customer, ship_to, shipped_at, created_by) values")
emit(",\n".join(ship_rows) + ";")
emit()
print("\n".join(out))
